EXAMPLE_PANELS = [
    {
        name: "Panel Retinitis Pigmentosa",
        "primaryDiseases": [
            {"name": "Ataxia_and_retinitis_pigmentosa_with_isolated_vitamin_e_deficiency"},
            {"name": "Hypoprebetalipoproteinemia,_acanthocytosis,_retinitis_pigmentosa,_and_pallidal_degeneration"},
            {"name": "Juvenile_retinitis_pigmentosa,_AIPL1-related"},
            {"name": "Neuropathy_ataxia_retinitis_pigmentosa_syndrome"},
            {"name": "POSTERIOR COLUMN ATAXIA WITH RETINITIS PIGMENTOSA"},
            {"name": "Polyneuropathy, hearing loss, ataxia, retinitis pigmentosa, and cataract"},
            {"name": "RETINITIS PIGMENTOSA 1"},
            {"name": "RETINITIS PIGMENTOSA 10"},
            {"name": "RETINITIS PIGMENTOSA 11"},
            {"name": "RETINITIS PIGMENTOSA 12"},
            {"name": "RETINITIS PIGMENTOSA 13"},
            {"name": "RETINITIS PIGMENTOSA 14"},
            {"name": "RETINITIS PIGMENTOSA 17"},
            {"name": "RETINITIS PIGMENTOSA 18"},
            {"name": "RETINITIS PIGMENTOSA 19"},
            {"name": "RETINITIS PIGMENTOSA 2"},
            {"name": "RETINITIS PIGMENTOSA 20"},
            {"name": "RETINITIS PIGMENTOSA 25"},
            {"name": "RETINITIS PIGMENTOSA 26"},
            {"name": "RETINITIS PIGMENTOSA 27"},
            {"name": "RETINITIS PIGMENTOSA 3"},
            {"name": "RETINITIS PIGMENTOSA 33"},
            {"name": "RETINITIS PIGMENTOSA 35"},
            {"name": "RETINITIS PIGMENTOSA 36"},
            {"name": "RETINITIS PIGMENTOSA 37"},
            {"name": "RETINITIS PIGMENTOSA 38"},
            {"name": "RETINITIS PIGMENTOSA 39"},
            {"name": "RETINITIS PIGMENTOSA 4"},
            {"name": "RETINITIS PIGMENTOSA 4, AUTOSOMAL RECESSIVE"},
            {"name": "RETINITIS PIGMENTOSA 40"},
            {"name": "RETINITIS PIGMENTOSA 41"},
            {"name": "RETINITIS PIGMENTOSA 42"},
            {"name": "RETINITIS PIGMENTOSA 43"},
            {"name": "RETINITIS PIGMENTOSA 44"},
            {"name": "RETINITIS PIGMENTOSA 45"},
            {"name": "RETINITIS PIGMENTOSA 46"},
            {"name": "RETINITIS PIGMENTOSA 48"},
            {"name": "RETINITIS PIGMENTOSA 49"},
            {"name": "RETINITIS PIGMENTOSA 50"},
            {"name": "RETINITIS PIGMENTOSA 54"},
            {"name": "RETINITIS PIGMENTOSA 56"},
            {"name": "RETINITIS PIGMENTOSA 57"},
            {"name": "RETINITIS PIGMENTOSA 61"},
            {"name": "RETINITIS PIGMENTOSA 66"},
            {"name": "RETINITIS PIGMENTOSA 7"},
            {"name": "RETINITIS PIGMENTOSA 7, DIGENIC"},
            {"name": "RETINITIS PIGMENTOSA 7, WITH BULL'S-EYE MACULOPATHY"},
            {"name": "RETINITIS PIGMENTOSA 9"},
            {"name": "RETINITIS PIGMENTOSA IN CILIOPATHIES, MODIFIER OF"},
            {"name": "RETINITIS PIGMENTOSA, JUVENILE, SPATA7-RELATED"},
            {"name": "RETINITIS PIGMENTOSA, X-LINKED, AND SINORESPIRATORY INFECTIONS, WITH DEAFNESS"},
            {"name": "RETINITIS PUNCTATA ALBESCENS"},
            {"name": "REtinitis pigmentosa 62"},
            {"name": "Retinitis Pigmentosa 28"},
            {"name": "Retinitis pigmentosa"},
            {"name": "Retinitis pigmentosa 58"},
            {"name": "Retinitis pigmentosa 59"},
            {"name": "Retinitis pigmentosa 60"},
            {"name": "Retinitis pigmentosa autosomal recessive"},
            {"name": "Retinitis pigmentosa type 1"},
            {"name": "Retinitis pigmentosa type 12"},
            {"name": "Retinitis pigmentosa type 2"},
            {"name": "Retinitis pigmentosa type 35"},
            {"name": "Retinitis pigmentosa type 39"},
            {"name": "Retinitis pigmentosa type 4"},
            {"name": "Retinitis_pigmentosa,_concentric"},
            {"name": "Retinitis_pigmentosa-deafness_syndrome"},
            {"name": "Retinitis_pigmentosa_15"},
            {"name": "Retinitis_pigmentosa_53"},
            {"name": "Retinitis_pigmentosa_64"},
            {"name": "Retinitis_pigmentosa_7,_with_bulls-eye_maculopathy"}
        ],
        "secondaryDiseases": [
            {"name": "USHER SYNDROME, TYPE IB"},
            {"name": "USHER SYNDROME, TYPE IC"},
            {"name": "USHER SYNDROME, TYPE ID"},
            {"name": "USHER SYNDROME, TYPE ID/F, DIGENIC"},
            {"name": "USHER SYNDROME, TYPE IF"},
            {"name": "USHER SYNDROME, TYPE IG"},
            {"name": "USHER SYNDROME, TYPE IIA"},
            {"name": "USHER SYNDROME, TYPE IIC"},
            {"name": "USHER SYNDROME, TYPE IID"},
            {"name": "USHER SYNDROME, TYPE IIIA"},
            {"name": "Usher syndrome 1B"},
            {"name": "Usher syndrome 1D"},
            {"name": "Usher syndrome 1F"},
            {"name": "Usher syndrome 2A"},
            {"name": "Usher syndrome type 1B"},
            {"name": "Usher syndrome type 1D"},
            {"name": "Usher syndrome type 2A"},
            {"name": "Usher_syndrome,_type_1B"},
            {"name": "Usher_syndrome,_type_1C"},
            {"name": "Usher_syndrome,_type_1D"},
            {"name": "Usher_syndrome,_type_1F"},
            {"name": "Usher_syndrome,_type_1G"},
            {"name": "Usher_syndrome,_type_2A"},
            {"name": "Usher_syndrome,_type_2C"},
            {"name": "Usher_syndrome,_type_2D"},
            {"name": "Usher_syndrome,_type_3"},
            {"name": "Usher_syndrome,_type_3B"}
        ],
        "genes": [
            {"name": "BEST1"},
            {"name": "C2orf71"},
            {"name": "CA4"},
            {"name": "CDH23"},
            {"name": "CERKL"},
            {"name": "CLRN1"},
            {"name": "CNGA1"},
            {"name": "CNGB1"},
            {"name": "CRB1"},
            {"name": "CRX"},
            {"name": "EYS"},
            {"name": "GPR98"},
            {"name": "GUCA1B"},
            {"name": "HPRP3"},
            {"name": "IDH3B"},
            {"name": "IMPDH1"},
            {"name": "IMPG2"},
            {"name": "KLHL7"},
            {"name": "MERTK"},
            {"name": "MYO7A"},
            {"name": "NR2E3"},
            {"name": "NRL"},
            {"name": "PCDH15"},
            {"name": "PDE6A"},
            {"name": "PDE6B"},
            {"name": "PDE6G"},
            {"name": "PRCD"},
            {"name": "PROM1"},
            {"name": "PRPF3"},
            {"name": "PRPF31"},
            {"name": "PRPF8"},
            {"name": "PRPH2"},
            {"name": "RDH5"},
            {"name": "RGR"},
            {"name": "RHO"},
            {"name": "RLBP1"},
            {"name": "RP1"},
            {"name": "RP2"},
            {"name": "RP9"},
            {"name": "RPE65"},
            {"name": "RPGR"},
            {"name": "RPGRIP1L"},
            {"name": "SANS"},
            {"name": "SEMA4A"},
            {"name": "SPATA7"},
            {"name": "TULP1"},
            {"name": "USH1C"},
            {"name": "USH1G"},
            {"name": "USH2A"},
            {"name": "WHRN"}
        ]
    },
    {
        name: "Comprehensive Cancer Design",
        primaryDiseases: [
            {name: "Cancer"}
        ],
        secondaryDiseases: [],
        genes: [
            { name: "ABCC6"},
            { name: "ABI1"},
            { name: "ABL1"},
            { name: "ABL2"},
            { name: "ACSL3"},
            { name: "ACSL6"},
            { name: "AFF1"},
            { name: "AFF3"},
            { name: "AFF4"},
            { name: "AIP"},
            { name: "AKAP9"},
            { name: "AKT1"},
            { name: "AKT2"},
            { name: "AKT3"},
            { name: "ALDH2"},
            { name: "ALK"},
            { name: "APC"},
            { name: "AR"},
            { name: "ARHGAP26"},
            { name: "ARHGEF12"},
            { name: "ARID1A"},
            { name: "ARID1B"},
            { name: "ARID2"},
            { name: "ARID3A"},
            { name: "ARID3B"},
            { name: "ARID4A"},
            { name: "ARID4B"},
            { name: "ARID5A"},
            { name: "ARID5B"},
            { name: "ARNT"},
            { name: "ASPSCR1"},
            { name: "ASXL1"},
            { name: "ATF1"},
            { name: "ATIC"},
            { name: "ATM"},
            { name: "ATR"},
            { name: "ATRX"},
            { name: "AURKA"},
            { name: "AXIN2"},
            { name: "BAP1"},
            { name: "BCL10"},
            { name: "BCL11A"},
            { name: "BCL11B"},
            { name: "BCL2"},
            { name: "BCL3"},
            { name: "BCL6"},
            { name: "BCL7A"},
            { name: "BCL9"},
            { name: "BCOR"},
            { name: "BCR"},
            { name: "BIRC3"},
            { name: "BLID"},
            { name: "BLM"},
            { name: "BMPR1A"},
            { name: "BRAF"},
            { name: "BRCA1"},
            { name: "BRCA2"},
            { name: "BRD3"},
            { name: "BRD4"},
            { name: "BRIP1"},
            { name: "BTG1"},
            { name: "BUB1B"},
            { name: "C15orf55"},
            { name: "CANT1"},
            { name: "CARD11"},
            { name: "CARS"},
            { name: "CASC5"},
            { name: "CBFA2T3"},
            { name: "CBFB"},
            { name: "CBL"},
            { name: "CBLB"},
            { name: "CBLC"},
            { name: "CCDC6"},
            { name: "CCNB1IP1"},
            { name: "CCND1"},
            { name: "CCND2"},
            { name: "CCND3"},
            { name: "CCNE1"},
            { name: "CD274"},
            { name: "CD74"},
            { name: "CD79A"},
            { name: "CD79B"},
            { name: "CDC73"},
            { name: "CDH1"},
            { name: "CDH11"},
            { name: "CDH6"},
            { name: "CDK12"},
            { name: "CDK2AP2"},
            { name: "CDK4"},
            { name: "CDK6"},
            { name: "CDK8"},
            { name: "CDKN1A"},
            { name: "CDKN1B"},
            { name: "CDKN2A"},
            { name: "CDKN2B"},
            { name: "CDKN2C"},
            { name: "CDKN2D"},
            { name: "CDX2"},
            { name: "CEBPA"},
            { name: "CHCHD7"},
            { name: "CHD5"},
            { name: "CHD6"},
            { name: "CHEK1"},
            { name: "CHEK2"},
            { name: "CHIC2"},
            { name: "CHN1"},
            { name: "CIC"},
            { name: "CIITA"},
            { name: "CLP1"},
            { name: "CLTC"},
            { name: "CLTCL1"},
            { name: "CNBP"},
            { name: "CNTRL"},
            { name: "COL1A1"},
            { name: "COX6C"},
            { name: "CREB1"},
            { name: "CREB3L1"},
            { name: "CREB3L2"},
            { name: "CREBBP"},
            { name: "CRKL"},
            { name: "CRLF2"},
            { name: "CRTC1"},
            { name: "CRTC3"},
            { name: "CSF1R"},
            { name: "CTNNB1"},
            { name: "CXCR7"},
            { name: "CYLD"},
            { name: "CYP1B1"},
            { name: "DAXX"},
            { name: "DDB2"},
            { name: "DDIT3"},
            { name: "DDX10"},
            { name: "DDX5"},
            { name: "DDX6"},
            { name: "DEK"},
            { name: "DICER1"},
            { name: "DNMT3A"},
            { name: "DUX4"},
            { name: "EBF1"},
            { name: "EGFR"},
            { name: "EIF4A2"},
            { name: "ELAC2"},
            { name: "ELF4"},
            { name: "ELK4"},
            { name: "ELL"},
            { name: "ELN"},
            { name: "EML4"},
            { name: "EP300"},
            { name: "EPCAM"},
            { name: "EPHA10"},
            { name: "EPHA3"},
            { name: "EPHA5"},
            { name: "EPHA6"},
            { name: "EPHB6"},
            { name: "EPS15"},
            { name: "ERBB2"},
            { name: "ERBB3"},
            { name: "ERBB4"},
            { name: "ERC1"},
            { name: "ERCC1"},
            { name: "ERCC2"},
            { name: "ERCC3"},
            { name: "ERCC4"},
            { name: "ERCC5"},
            { name: "ERG"},
            { name: "ETV1"},
            { name: "ETV4"},
            { name: "ETV5"},
            { name: "ETV6"},
            { name: "EWSR1"},
            { name: "EXT1"},
            { name: "EXT2"},
            { name: "EZH2"},
            { name: "FAM123B"},
            { name: "FAM22A"},
            { name: "FAM22B"},
            { name: "FAM46C"},
            { name: "FANCA"},
            { name: "FANCC"},
            { name: "FANCD2"},
            { name: "FANCE"},
            { name: "FANCF"},
            { name: "FANCG"},
            { name: "FAS"},
            { name: "FBXO11"},
            { name: "FBXW7"},
            { name: "FCGR2B"},
            { name: "FCRL4"},
            { name: "FEV"},
            { name: "FGF23"},
            { name: "FGFR1"},
            { name: "FGFR1OP"},
            { name: "FGFR2"},
            { name: "FGFR3"},
            { name: "FGFR4"},
            { name: "FH"},
            { name: "FHIT"},
            { name: "FHL1"},
            { name: "FIP1L1"},
            { name: "FKBP1B"},
            { name: "FKBP9"},
            { name: "FLCN"},
            { name: "FLI1"},
            { name: "FLT1"},
            { name: "FLT3"},
            { name: "FLT4"},
            { name: "FNBP1"},
            { name: "FOLR1"},
            { name: "FOXC1"},
            { name: "FOXL2"},
            { name: "FOXO1"},
            { name: "FOXO3"},
            { name: "FOXO4"},
            { name: "FOXP1"},
            { name: "FSTL3"},
            { name: "FUBP1"},
            { name: "FUS"},
            { name: "GALNT3"},
            { name: "GAS7"},
            { name: "GATA1"},
            { name: "GATA2"},
            { name: "GATA3"},
            { name: "GLMN"},
            { name: "GMPS"},
            { name: "GNA11"},
            { name: "GNAQ"},
            { name: "GNAS"},
            { name: "GOLGA5"},
            { name: "GOPC"},
            { name: "GPC3"},
            { name: "GPHN"},
            { name: "GSTM1"},
            { name: "GUCY1A2"},
            { name: "HECW1"},
            { name: "HERPUD1"},
            { name: "HEY1"},
            { name: "HIP1"},
            { name: "HIST1H4I"},
            { name: "HLF"},
            { name: "HMGA1"},
            { name: "HMGA2"},
            { name: "HMGN2P46"},
            { name: "HNF1A"},
            { name: "HNRNPA2B1"},
            { name: "HOOK3"},
            { name: "HOXA11"},
            { name: "HOXA13"},
            { name: "HOXA9"},
            { name: "HOXC11"},
            { name: "HOXC13"},
            { name: "HOXD11"},
            { name: "HOXD13"},
            { name: "HRAS"},
            { name: "HSD17B3"},
            { name: "HSD3B2"},
            { name: "HSP90AA1"},
            { name: "HSP90AB1"},
            { name: "IDH1"},
            { name: "IDH2"},
            { name: "IGF1R"},
            { name: "IKBKE"},
            { name: "IKZF1"},
            { name: "IL2"},
            { name: "IL21R"},
            { name: "IL6ST"},
            { name: "IL7R"},
            { name: "IRF4"},
            { name: "ITK"},
            { name: "JAK1"},
            { name: "JAK2"},
            { name: "JAK3"},
            { name: "JAZF1"},
            { name: "JUN"},
            { name: "KAT6A"},
            { name: "KAT6B"},
            { name: "KDM5A"},
            { name: "KDM5C"},
            { name: "KDM6A"},
            { name: "KDR"},
            { name: "KDSR"},
            { name: "KEAP1"},
            { name: "KIAA1549"},
            { name: "KIF1B"},
            { name: "KIT"},
            { name: "KL"},
            { name: "KLF6"},
            { name: "KLK2"},
            { name: "KRAS"},
            { name: "KRT17"},
            { name: "KTN1"},
            { name: "LASP1"},
            { name: "LCK"},
            { name: "LCP1"},
            { name: "LHFP"},
            { name: "LIFR"},
            { name: "LMO1"},
            { name: "LMO2"},
            { name: "LPP"},
            { name: "LRP5"},
            { name: "LTBP2"},
            { name: "LTBP3"},
            { name: "LYL1"},
            { name: "MAD2L1BP"},
            { name: "MAF"},
            { name: "MAFB"},
            { name: "MALAT1"},
            { name: "MALT1"},
            { name: "MAML2"},
            { name: "MAP2K1"},
            { name: "MAP2K2"},
            { name: "MAP2K4"},
            { name: "MAP3K1"},
            { name: "MAP3K8"},
            { name: "MAX"},
            { name: "MC1R"},
            { name: "MCL1"},
            { name: "MDM2"},
            { name: "MDM4"},
            { name: "MDS2"},
            { name: "MECOM"},
            { name: "MED12"},
            { name: "MEN1"},
            { name: "MET"},
            { name: "MITF"},
            { name: "MKL1"},
            { name: "MLF1"},
            { name: "MLH1"},
            { name: "MLL"},
            { name: "MLL2"},
            { name: "MLL3"},
            { name: "MLLT1"},
            { name: "MLLT10"},
            { name: "MLLT11"},
            { name: "MLLT3"},
            { name: "MLLT4"},
            { name: "MLLT6"},
            { name: "MN1"},
            { name: "MNX1"},
            { name: "MPL"},
            { name: "MRE11A"},
            { name: "MSH2"},
            { name: "MSH6"},
            { name: "MSI2"},
            { name: "MSN"},
            { name: "MTCP1"},
            { name: "MTCP1NB"},
            { name: "MTOR"},
            { name: "MTUS2"},
            { name: "MUC1"},
            { name: "MUTYH"},
            { name: "MYB"},
            { name: "MYC"},
            { name: "MYCL1"},
            { name: "MYCN"},
            { name: "MYD88"},
            { name: "MYH11"},
            { name: "MYH9"},
            { name: "MYOC"},
            { name: "NACA"},
            { name: "NBN"},
            { name: "NCKIPSD"},
            { name: "NCOA1"},
            { name: "NCOA2"},
            { name: "NCOA4"},
            { name: "NDRG1"},
            { name: "NF1"},
            { name: "NF2"},
            { name: "NFE2L2"},
            { name: "NFIB"},
            { name: "NFKB2"},
            { name: "NIN"},
            { name: "NKX2-1"},
            { name: "NONO"},
            { name: "NOTCH1"},
            { name: "NOTCH2"},
            { name: "NOTCH3"},
            { name: "NOTCH4"},
            { name: "NPM1"},
            { name: "NR4A3"},
            { name: "NRAS"},
            { name: "NSD1"},
            { name: "NTRK1"},
            { name: "NTRK2"},
            { name: "NTRK3"},
            { name: "NUMA1"},
            { name: "NUP214"},
            { name: "NUP98"},
            { name: "OLIG2"},
            { name: "OMD"},
            { name: "OPTN"},
            { name: "P2RY8"},
            { name: "PAFAH1B2"},
            { name: "PAK7"},
            { name: "PALB2"},
            { name: "PALLD"},
            { name: "PATZ1"},
            { name: "PAX2"},
            { name: "PAX3"},
            { name: "PAX5"},
            { name: "PAX6"},
            { name: "PAX7"},
            { name: "PAX8"},
            { name: "PBRM1"},
            { name: "PBX1"},
            { name: "PCM1"},
            { name: "PCSK7"},
            { name: "PDCD1LG2"},
            { name: "PDE4DIP"},
            { name: "PDGFB"},
            { name: "PDGFRA"},
            { name: "PDGFRB"},
            { name: "PDPK1"},
            { name: "PER1"},
            { name: "PHF6"},
            { name: "PHOX2B"},
            { name: "PICALM"},
            { name: "PIK3CA"},
            { name: "PIK3R1"},
            { name: "PIM1"},
            { name: "PLAG1"},
            { name: "PLK1"},
            { name: "PML"},
            { name: "PMS1"},
            { name: "PMS2"},
            { name: "POU2AF1"},
            { name: "POU5F1"},
            { name: "PPARG"},
            { name: "PPP2R1A"},
            { name: "PRCC"},
            { name: "PRDM1"},
            { name: "PRDM16"},
            { name: "PRF1"},
            { name: "PRKAR1A"},
            { name: "PRKDC"},
            { name: "PRRX1"},
            { name: "PSIP1"},
            { name: "PTCH1"},
            { name: "PTEN"},
            { name: "PTK2"},
            { name: "PTK2B"},
            { name: "PTPN11"},
            { name: "PTPRD"},
            { name: "RABEP1"},
            { name: "RAD51B"},
            { name: "RAF1"},
            { name: "RALGDS"},
            { name: "RANBP17"},
            { name: "RAP1GDS1"},
            { name: "RARA"},
            { name: "RB1"},
            { name: "RBM15"},
            { name: "RECQL4"},
            { name: "REL"},
            { name: "RET"},
            { name: "RHOH"},
            { name: "RICTOR"},
            { name: "RMI2"},
            { name: "RNASEL"},
            { name: "ROS1"},
            { name: "RPL22"},
            { name: "RPN1"},
            { name: "RPTOR"},
            { name: "RRM1"},
            { name: "RUNX1"},
            { name: "RUNX1T1"},
            { name: "SARDH"},
            { name: "SBDS"},
            { name: "SDHAF2"},
            { name: "SDHB"},
            { name: "SDHC"},
            { name: "SDHD"},
            { name: "SEPT5"},
            { name: "SEPT6"},
            { name: "SEPT9"},
            { name: "SET"},
            { name: "SETD2"},
            { name: "SETDB1"},
            { name: "SF3B1"},
            { name: "SF3B2"},
            { name: "SFPQ"},
            { name: "SH3GL1"},
            { name: "SLC45A3"},
            { name: "SMAD2"},
            { name: "SMAD3"},
            { name: "SMAD4"},
            { name: "SMARCA4"},
            { name: "SMARCB1"},
            { name: "SMO"},
            { name: "SNX29"},
            { name: "SOCS1"},
            { name: "SOX2"},
            { name: "SPECC1"},
            { name: "SPEN"},
            { name: "SRC"},
            { name: "SRD5A2"},
            { name: "SRGAP3"},
            { name: "SRSF2"},
            { name: "SRSF3"},
            { name: "SS18"},
            { name: "SS18L1"},
            { name: "SSX1"},
            { name: "SSX2"},
            { name: "SSX4"},
            { name: "STAT3"},
            { name: "STIL"},
            { name: "STK11"},
            { name: "STX11"},
            { name: "STXBP2"},
            { name: "SUFU"},
            { name: "SUZ12"},
            { name: "SYK"},
            { name: "TAF15"},
            { name: "TAL1"},
            { name: "TAL2"},
            { name: "TCEA1"},
            { name: "TCEA1P2"},
            { name: "TCF12"},
            { name: "TCF3"},
            { name: "TCF4"},
            { name: "TCF7L2"},
            { name: "TCL1A"},
            { name: "TCL6"},
            { name: "TERT"},
            { name: "TET1"},
            { name: "TET2"},
            { name: "TFE3"},
            { name: "TFEB"},
            { name: "TFG"},
            { name: "TFPT"},
            { name: "TFRC"},
            { name: "TGFBR2"},
            { name: "THRAP3"},
            { name: "TLX1"},
            { name: "TLX3"},
            { name: "TMEM127"},
            { name: "TMPRSS2"},
            { name: "TNFAIP3"},
            { name: "TNFRSF14"},
            { name: "TNFRSF17"},
            { name: "TOP1"},
            { name: "TOP2A"},
            { name: "TP53"},
            { name: "TPM3"},
            { name: "TPM4"},
            { name: "TPR"},
            { name: "TRIM24"},
            { name: "TRIM27"},
            { name: "TRIM33"},
            { name: "TRIP11"},
            { name: "TSC1"},
            { name: "TSC2"},
            { name: "TSHR"},
            { name: "TTL"},
            { name: "TYK2"},
            { name: "U2AF1"},
            { name: "UNC13D"},
            { name: "USP6"},
            { name: "UTY"},
            { name: "VHL"},
            { name: "VTI1A"},
            { name: "WAS"},
            { name: "WDR36"},
            { name: "WHSC1"},
            { name: "WHSC1L1"},
            { name: "WIF1"},
            { name: "WRN"},
            { name: "WT1"},
            { name: "XPA"},
            { name: "XPC"},
            { name: "XPO1"},
            { name: "YWHAE"},
            { name: "ZBTB16"},
            { name: "ZMYM2"},
            { name: "ZNF331"},
            { name: "ZNF384"},
            { name: "ZNF521"},
            { name: "ZNF668"},
            { name: "ZRSR2"}
        ]
    }
]
